---
- name: reboot
  become: true
  shell: shutdown -r
  ignore_errors: yes
  async: 0
  poll: 0
  notify: Wait for server to reboot

- name: Wait for server to reboot
  wait_for_connection:
    delay: 75
    timeout: 300

- name: update_grub
  become: true
  command: update-grub
  changed_when: true
  notify: reboot