---
- name: Ensure cloud-init in installed
  ansible.builtin.package:
    name: cloud-init
    state: present

- name: Ensure cloud-init.service is enabled
  ansible.builtin.service:
    name: cloud-init.service
    enabled: true